name: SimpleEconomy
version: 1.0.0
main: rark\simple_economy\Main
api: 4.0.0
author: RarkHopper
permissions:
  simple_economy.command.op:
    escription: "Allows the user to run the example command"
    default: op # can also be false, or op
  simple_economy.command.public:
    description: "Allows the user to run the example command"
    default: true # can also be false, or op
