'currencies':
  'yen': #通貨の名前
    'prefix': '￥'
    #true => 数字の先頭  $1,000
    #false => 数字の後ろ 1,000$
    'prefix_position': true
    'default': 1000 #最初にプレイヤーが持っている所持金
    
  'dollar': 
    'prefix': '$'
    'prefix_position': true
    'default': 1000
